const MyData=[
        {
            id:0,
            name:"John",
            age:23
        },
        {
            id:1,
            name:"Akshay",
            age:25
        },
        {
            id:2,
            name:"Rahul",
            age:25
        },
        {
            id:3,
            name:"Aryan",
            age:26
        },
        {
            id:4,
            name:"Alexa",
            age:29
        },
        {   id:5,
            name:"Simran",
            age:25
        },
        {
            id:6,
            name:"Bob",
            age:25
        },
        {
            id:7,
            name:"Alex",
            age:24
        },
        {
            id:8,
            name:"Doe",
            age:27
        },
        {
            id:9,
            name:"Smith",
            age:28
        }
    ]
export default MyData;